# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrambler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_hash', models.CharField(max_length=32, unique=True, verbose_name='Url')),
                ('expires', models.DateTimeField(verbose_name='Expires')),
            ],
        ),
    ]
