# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrambler', '0007_auto_20170722_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='5f6g7h8', max_length=255)),
            ],
        ),
    ]
