# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrambler', '0008_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ExpirationLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='5f6g7h8', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExpiringURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Ledger',
        ),
        migrations.AddField(
            model_name='profile',
            name='total_size_of_uploaded_images',
            field=models.BigIntegerField(default=0),
        ),
    ]
