# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 18:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrambler', '0009_auto_20170723_1256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpirationLedger',
        ),
        migrations.AddField(
            model_name='expiringurl',
            name='expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 23, 19, 35, 0, 329475), editable=False),
        ),
        migrations.AddField(
            model_name='expiringurl',
            name='url',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 23, 19, 35, 0, 327470)),
        ),
    ]
