# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 18:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrambler', '0010_auto_20170723_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringurl',
            name='expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 23, 19, 39, 59, 845609), editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 23, 19, 39, 59, 845110)),
        ),
    ]
