# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 18:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrambler', '0014_auto_20170723_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiringurl',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expiringurl',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 23, 19, 49, 43, 783388)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 23, 19, 49, 43, 782888)),
        ),
    ]
