# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 19:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrambler', '0016_auto_20170723_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringurl',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 23, 20, 59, 39, 708206)),
        ),
        migrations.AlterField(
            model_name='expiringurl',
            name='url',
            field=models.CharField(default=0, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 23, 20, 59, 39, 707705)),
        ),
    ]
