# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 22:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scrambler', '0024_auto_20170723_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiringurl',
            name='mode',
            field=models.CharField(default='Scramble', max_length=255),
        ),
        migrations.AlterField(
            model_name='expiringurl',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 23, 22, 30, 58, 178660, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 23, 22, 30, 58, 177660, tzinfo=utc)),
        ),
    ]
