# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 23:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scrambler', '0027_auto_20170724_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_file_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expiringurl',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 23, 23, 16, 21, 625553, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 23, 23, 16, 21, 623556, tzinfo=utc)),
        ),
    ]
