# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 15:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scrambler', '0029_auto_20170724_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.date(2017, 7, 24))),
                ('dau', models.IntegerField(default=0)),
                ('interaction_count', models.IntegerField(default=0)),
                ('scram_count', models.IntegerField(default=0)),
                ('unscram_count', models.IntegerField(default=0)),
                ('total_files', models.IntegerField(default=0)),
                ('login_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='AnalyticsLedger',
        ),
        migrations.AlterField(
            model_name='expiringurl',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 15, 57, 58, 997228, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 15, 57, 58, 981605, tzinfo=utc), null=True),
        ),
    ]
