# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 16:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scrambler', '0030_auto_20170724_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expiringurl',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='expiringurl',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 16, 1, 29, 282885, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 16, 1, 29, 282885, tzinfo=utc), null=True),
        ),
    ]
