# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 16:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scrambler', '0031_auto_20170724_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiringurl',
            name='user_name',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='expiringurl',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 16, 13, 50, 592793, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 16, 13, 50, 577181, tzinfo=utc), null=True),
        ),
    ]
