# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 18:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scrambler', '0032_auto_20170724_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default=0, max_length=255, unique=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2017, 7, 24, 18, 39, 11, 250530, tzinfo=utc), null=True)),
                ('number_of_files', models.IntegerField(default=0)),
                ('user_name', models.CharField(default=0, max_length=255)),
                ('mode', models.CharField(default='Scramble', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='expiringurl',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 18, 39, 11, 249530, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 18, 39, 11, 249011, tzinfo=utc), null=True),
        ),
    ]
