# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 19:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scrambler', '0033_auto_20170724_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyledger',
            name='date',
            field=models.DateTimeField(default=datetime.date(2017, 7, 24), unique=True),
        ),
        migrations.AlterField(
            model_name='expiredurl',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 19, 35, 24, 940492, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='expiringurl',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 19, 35, 24, 939491, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 19, 35, 24, 938990, tzinfo=utc), null=True),
        ),
    ]
