# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 19:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrambler', '0034_auto_20170724_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyledger',
            name='date',
            field=models.DateTimeField(default=datetime.date(2017, 7, 25), unique=True),
        ),
        migrations.AlterField(
            model_name='expiredurl',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='expiringurl',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
