# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrambler', '0037_expiringurl_down_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test_user',
            field=models.BooleanField(default=False),
        ),
    ]
