# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrambler', '0038_profile_test_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userkey',
            field=models.CharField(default=0, max_length=255, unique=True),
        ),
    ]
