# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrambler', '0039_profile_userkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userkey',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
