# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrambler', '0040_auto_20170905_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default=0, max_length=255)),
                ('token', models.CharField(default=0, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RemoteToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default=0, max_length=255)),
                ('token', models.CharField(default=0, max_length=255)),
                ('uses', models.IntegerField(default=0)),
            ],
        ),
    ]
