# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrambler', '0041_expiredtoken_remotetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_id', models.CharField(default=0, max_length=255, unique=True)),
                ('user_name', models.CharField(default=0, max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('mode', models.CharField(default='Scramble', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='dailyledger',
            name='api_requests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyledger',
            name='api_scrams',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyledger',
            name='api_unscrams',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='api_requests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='api_scrams',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='api_unscrams',
            field=models.IntegerField(default=0),
        ),
    ]
